### PR TITLE
added-nandhagopan's-intro

### PR DESCRIPTION
**Pull request by NANDHAGOPN**
can u add my readme.md file

### CODE REVIEW

**Comment by suryan-s** [comment]
@arjunindia why is all the files shown as edited?

**Comment by arjunindia** [comment]
@suryan-s I have no idea :/ 
It could be a text encoding issue or something they did wrong

**Comment by NANDHAGOPN** [comment]
can you share me the commands for making the cloning and pull request

**Comment by arjunindia** [comment]
@NANDHAGOPN for cloning you use 
`git clone <link to repository>`
Make sure you are cloning your fork
Make the changes
You then commit and push to your fork with
`git commit -m"a commit message here"
git push`

**Pull request closed without merging**
